server:
  port: 443  #0 随机端口
  ssl:
    key-store: keystore.p12
    key-store-password: springboot
    keyStoreType: PKCS12
    keyAlias: tomcat
spring:
  application:
    name: spring
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/gwy?autoreconnect=true"
    password: "mecomysql"
    username: "root"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000

mybatis-plus:
  type-aliases-package: com.meco.spinrgdemo.pojo
  mapper-locations: classpath:mappers/*.xml


